version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3000:3306" 
    environment:
      MYSQL_DATABASE: backend
      MYSQL_USER: back_end_user 
      MYSQL_PASSWORD: back_end_user_password_01//@
      MYSQL_ROOT_PASSWORD: your_mysql_root_password  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
