version: '3'

services:
  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    image: ucefpingo/crawler:latest
    volumes:
      - .:/app

  extractor:
    build:
      context: .
      dockerfile: extractor/Dockerfile
    image: ucefpingo/extractor:latest
    volumes:
      - .:/app

  article_service:
    build:
      context: .
      dockerfile: ArticleService/Dockerfile
    ports:
      - "8000:8000"
    image: ucefpingo/article_service:latest
    volumes:
      - .:/app

  site_service:
    build:
      context: .
      dockerfile: SiteService/Dockerfile
    ports:
      - "8000:8000"
    image: ucefpingo/site_service:latest
    volumes:
      - .:/app

