apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
      - name: article-service
        image: ucefpingo/article_service:latest 
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: article-service-service
spec:
  selector:
    app: article-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  
