apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      containers:
      - name: extractor-container
        image: ucefpingo/extractor:latest

