# Generated by Django 4.1.13 on 2023-11-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_url', models.CharField(max_length=255)),
                ('article_xpath', models.CharField(max_length=255)),
                ('title_xpath', models.CharField(max_length=255)),
                ('body_xpath', models.CharField(max_length=255)),
                ('author_xpath', models.CharField(max_length=255)),
                ('date_xpath', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
