name: Test/Build/Push/Deploy extractor 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v2
    - name: GitHub Tag Name example
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install -r crawler/requirements.txt
            
            
    - uses: actions/checkout@v4
    - name: Run tests 
      run: python crawler/test.py -v
      
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker image
      run: docker build -t ucefpingo/crawler -f crawler/Dockerfile .


    - name: Push Docker image
      run: docker push ucefpingo/crawler:latest

      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 octopus-cluster-youssef
      
    - name: Rollout deployment
      run: kubectl rollout restart deployment crawler-deployment

    
