name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      
    - name: List files in the repository
      run: ls -al
      
    - name: Build Docker image
      run: docker build -t ucefpingo/crawler -f crawler/Dockerfile .

    - name: Push Docker image
      run: docker push ucefpingo/crawler:latest

      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 octopus-cluster-youssef
      
    - name: Show deployment
      run: kubectl get deployment
